# Generated by Django 6.0.2 on 2026-02-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='max_guests_per_resident',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='max_total_guests',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='residentprofile',
            index=models.Index(fields=['is_active'], name='coreapp_res_is_acti_a9eeda_idx'),
        ),
    ]
