# Generated by Django 6.0.2 on 2026-02-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_amenity_max_guests_per_resident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='address_city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='address_state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
