# Generated by Django 6.0.2 on 2026-02-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_residentprofile_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentprofile',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='residentprofile',
            name='address_postal_code',
        ),
        migrations.RemoveField(
            model_name='residentprofile',
            name='address_state',
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='residentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user',), name='unique_active_resident_per_user'),
        ),
    ]
