# Generated by Django 6.0.2 on 2026-02-27 05:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
