# Generated by Django 6.0.2 on 2026-02-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_alter_property_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_temp_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
