# Generated by Django 6.0.2 on 2026-02-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('coreapp', '0007_user_last_temp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='TENANT', max_length=16),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='coreapp_use_role_2c5b90_idx'),
        ),
    ]
