# Generated by Django 6.0.2 on 2026-02-27 18:52

from django.db import migrations, models


def map_admin_to_manager(apps, schema_editor):
    User = apps.get_model("coreapp", "User")
    User.objects.filter(role="ADMIN").update(role="MANAGER")


def reverse_noop(apps, schema_editor):
    # No reverse mapping; MANAGER stays MANAGER.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_user_role_user_coreapp_use_role_2c5b90_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('MANAGER', 'Manager')], default='TENANT', max_length=16),
        ),
        migrations.RunPython(map_admin_to_manager, reverse_noop),
    ]
