# Generated by Django 6.0.2 on 2026-02-27 18:55

from django.db import migrations, models


def clear_superuser_role(apps, schema_editor):
    User = apps.get_model("coreapp", "User")
    User.objects.filter(is_superuser=True).update(role=None)


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('TENANT', 'Tenant'), ('MANAGER', 'Manager')], default=None, max_length=16, null=True),
        ),
        migrations.RunPython(clear_superuser_role, reverse_noop),
    ]
