# Generated by Django 6.0.2 on 2026-02-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('MANAGER', 'Manager')], default='TENANT', max_length=16),
        ),
    ]
