# Generated by Django 5.1.4 on 2026-03-13 00:46

import coreapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_amenitycheckintoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='amenitycheckintoken',
            new_name='coreapp_ame_token_17f35b_idx',
            old_name='coreapp_amen_token_8fbc86_idx',
        ),
        migrations.RenameIndex(
            model_name='amenitycheckintoken',
            new_name='coreapp_ame_amenity_2c1143_idx',
            old_name='coreapp_amen_amenity__8f2e74_idx',
        ),
        migrations.RenameIndex(
            model_name='amenitycheckintoken',
            new_name='coreapp_ame_is_acti_008c9a_idx',
            old_name='coreapp_amen_is_active_4b8cf3_idx',
        ),
        migrations.AlterField(
            model_name='amenitycheckintoken',
            name='expires_at',
            field=models.DateTimeField(default=coreapp.models.default_token_expiry),
        ),
    ]
